app/modules/categories/models.py
import peewee
from app.modules.core import models as core


'''
class: Movie Category
'''
class MovieCategory(core.BaseModel):

  name = peewee.CharField(unique=True)

app/modules/categories/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class CategoryForm(FlaskForm):
  
  name = StringField('Name', validators=[DataRequired()])

app/modules/categories/controllers.py
# # Import flask dependencies
import peewee
from flask import Blueprint, render_template, request, redirect, url_for

# Import module models (i.e. User)
from .models import MovieCategory
from .forms import CategoryForm


# Define the blueprint: 'categories', set its url prefix: app.url/categories
blueprint = Blueprint('categories', __name__, url_prefix='/categories')


# ~~~~~~~~~~~~~
@blueprint.route('/', methods=['GET'])
def index():
  categories = MovieCategory.select().order_by(MovieCategory.name.desc())

  return render_template('categories/list.html', categories=categories)


# ~~~~~~~~~~~~~
@blueprint.route('/detail/<int:category_id>', methods=['GET'])
def detail(category_id):
  category = MovieCategory.get(id=category_id)

  return render_template('categories/detail.html', category=category)


# ~~~~~~~~~~~~~
@blueprint.route('/create', methods=['GET'])
def formGet():
  form = CategoryForm(request.form)
  return render_template('categories/form.html', form=form)


@blueprint.route('/create', methods=['POST'])
def formPost():
  form = CategoryForm(request.form)
  if form.validate_on_submit():

    try:
      MovieCategory.create(name=form.name.data)
    except peewee.IntegrityError:
      return render_template('categories/form.html', error='Categoria já cadastrada!', form=form)

    return redirect(url_for('categories.index'))

  return render_template('categories/form.html', form=form)


# ~~~~~~~~~~~~~
@blueprint.route('/update/<int:category_id>', methods=['GET', 'POST'])
def formUpdate(category_id):
  category = MovieCategory.get(id=category_id)
  form = CategoryForm(request.form, obj=category)

  if request.method == 'GET':
    return render_template('categories/update.html', category=category, form=form)

  else:
    if request.form['name']:

      try:
        category.name = request.form['name']
        category.save()
      except peewee.IntegrityError:
        return render_template('categories/update.html', category=category, error='Categoria já cadastrada!', form=form)

      return redirect(url_for('categories.index'))
      
    return render_template('categories/update.html', category=category, form=form)

app/modules/movies/controllers.py
# # Import flask dependencies
import peewee
from flask import Blueprint, render_template, request, redirect, url_for

# Import module models (i.e. User)
from .models import Movie
from .forms import MovieForm

from app.modules.categories.models import MovieCategory


# Define the blueprint: 'categories', set its url prefix: app.url/categories
blueprint = Blueprint('movies', __name__, url_prefix='/movies')




# ~~~~~~~~~~~~~
@blueprint.route('/', methods=['GET'])
def index():
  movies = Movie.select().order_by(Movie.name)

  return render_template('movies/list.html', movies=movies)


# ~~~~~~~~~~~~~
@blueprint.route('/detail/<int:movie_id>', methods=['GET'])
def detail(movie_id):
  movie = Movie.get(id=movie_id)

  return render_template('movies/detail.html', movie=movie)


# ~~~~~~~~~~~~~
@blueprint.route('/create', methods=['GET', 'POST'])
def formCreate():
  categories = [(b.id, b.name) for b in MovieCategory.select()]

  form = MovieForm(request.form)
  form.category.choices = categories

  if request.method == 'GET':
    return render_template('movies/form.html', form=form)

  else:
    if form.validate_on_submit():
      try:
        Movie.create(name=form.name.data, category=form.category.data)
      except peewee.IntegrityError:
        return render_template('movies/form.html', error='Filma já cadastrado!', form=form)

      return redirect(url_for('movies.index'))

    return render_template('movies/form.html', form=form)


# ~~~~~~~~~~~~~
@blueprint.route('/update/<int:movie_id>', methods=['GET', 'POST'])
def formUpdate(movie_id):
  movie = Movie.get(id=movie_id)
  categories = [(b.id, b.name) for b in MovieCategory.select()]

  form = MovieForm(request.form, obj=movie)
  form.category.choices = categories
  
  if request.method == 'GET':
    form.category.data = movie.category.id
    return render_template('movies/update.html', movie=movie, form=form)

  else:
    if form.validate_on_submit():
      try:
        movie.name = form.name.data
        movie.category = form.category.data
        movie.save()
      except peewee.IntegrityError:
        return render_template('movies/update.html', error='Filma já cadastrado!', form=form)

      return redirect(url_for('movies.index'))

    return render_template('movies/update.html', form=form, movie=movie)

app/templates/categories/detail.html
{% extends 'core/base.html' %}

{% block hero %}
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        {{ category.name }}
      </h1>
      <h2 class="subtitle">
        Veja os filmes da categoria <b>{{ category.name }}</b>
      </h2>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
  {% for movie in category.movies %}
  <button class="button is-light is-large"><a href="{{ url_for('movies.detail', movie_id=movie.id) }}">{{ movie.name }}</a></button>
  {% endfor %}
  <button class="button is-info is-light"><a href="{{ url_for('categories.formUpdate', category_id=category.id) }}">Editar</a></button>
{% endblock %}

app/templates/categories/form.html
{% extends 'core/base.html' %}

{% block hero %}
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Categorias
      </h1>
      <h2 class="subtitle">
        Informe o nome da nova categoria
      </h2>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
  {% if error %}
  <div class="notification is-danger">
    {{ error }}
  </div>
  {% endif %}

  <form action="{{ url_for('categories.formPost') }}" method="POST">
    {{ form.csrf_token }}
    <div class="field">
      <label class="label">Name</label>
      <div class="control">
        {{ form.name(size=20, class_="input") }}
      </div>
    </div>
    <div class="control">
      <button class="button is-primary">Salvar</button>
    </div>    
  </form>
{% endblock %}

app/templates/categories/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FlaskMovies - Categorias</title>
</head>
<body>
  <h1>Categorias</h1>
  <ul>
    {% for category in categories %}
    <li>{{ category.name }}</li>
    {% endfor %}
  </ul>  
</body>
</html>

app/templates/categories/list.html
{% extends 'core/base.html' %}

{% block hero %}
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Categorias
      </h1>
      <h2 class="subtitle">
        Escolha as categorias do filme
      </h2>
    </div>
  </div>
</section>
{% endblock %}
{% block content %}
  {% for category in categories %}
  <button class="button is-light is-large"><a href="{{ url_for('categories.detail', category_id=category.id) }}">{{ category.name }}</a></button>
  {% endfor %}
  <button class="button is-info is-light is-large"><a href="{{ url_for('categories.formGet') }}">Nova categoria</a></button>
{% endblock %}

app/templates/categories/update.html
{% extends 'core/base.html' %}

{% block hero %}
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Categorias
      </h1>
      <h2 class="subtitle">
        Atualize o nome da categoria
      </h2>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
  {% if error %}
  <div class="notification is-danger">
    {{ error }}
  </div>
  {% endif %}

  <form action="{{ url_for('categories.formUpdate', category_id=category.id) }}" method="POST">
    {{ form.csrf_token }}
    <div class="field">
      <label class="label">Name</label>
      <div class="control">
        {{ form.name(size=20, class_="input") }}
      </div>
    </div>
    <div class="control">
      <button class="button is-primary">Salvar</button>
    </div>    
  </form>
{% endblock %}