app/modules/movies/models.py
import peewee
from app.modules.core import models as core
from app.modules.categories import models as categories


'''
class: Movie
'''
class Movie(core.BaseModel):

  name = peewee.CharField(unique=True)
  category = peewee.ForeignKeyField(categories.MovieCategory, backref='movies')

app/modules/movies/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField
from wtforms.validators import DataRequired

class MovieForm(FlaskForm):
  
  name = StringField('Name', validators=[DataRequired()])
  category = SelectField('Categoria', coerce=int)

app/modules/movies/controllers.py
# # Import flask dependencies
import peewee
from flask import Blueprint, render_template, request, redirect, url_for

# Import module models (i.e. User)
from .models import Movie
from .forms import MovieForm

from app.modules.categories.models import MovieCategory


# Define the blueprint: 'categories', set its url prefix: app.url/categories
blueprint = Blueprint('movies', __name__, url_prefix='/movies')




# ~~~~~~~~~~~~~
@blueprint.route('/', methods=['GET'])
def index():
  movies = Movie.select().order_by(Movie.name)

  return render_template('movies/list.html', movies=movies)


# ~~~~~~~~~~~~~
@blueprint.route('/detail/<int:movie_id>', methods=['GET'])
def detail(movie_id):
  movie = Movie.get(id=movie_id)

  return render_template('movies/detail.html', movie=movie)


# ~~~~~~~~~~~~~
@blueprint.route('/create', methods=['GET', 'POST'])
def formCreate():
  categories = [(b.id, b.name) for b in MovieCategory.select()]

  form = MovieForm(request.form)
  form.category.choices = categories

  if request.method == 'GET':
    return render_template('movies/form.html', form=form)

  else:
    if form.validate_on_submit():
      try:
        Movie.create(name=form.name.data, category=form.category.data)
      except peewee.IntegrityError:
        return render_template('movies/form.html', error='Filma já cadastrado!', form=form)

      return redirect(url_for('movies.index'))

    return render_template('movies/form.html', form=form)


# ~~~~~~~~~~~~~
@blueprint.route('/update/<int:movie_id>', methods=['GET', 'POST'])
def formUpdate(movie_id):
  movie = Movie.get(id=movie_id)
  categories = [(b.id, b.name) for b in MovieCategory.select()]

  form = MovieForm(request.form, obj=movie)
  form.category.choices = categories
  
  if request.method == 'GET':
    form.category.data = movie.category.id
    return render_template('movies/update.html', movie=movie, form=form)

  else:
    if form.validate_on_submit():
      try:
        movie.name = form.name.data
        movie.category = form.category.data
        movie.save()
      except peewee.IntegrityError:
        return render_template('movies/update.html', error='Filma já cadastrado!', form=form)

      return redirect(url_for('movies.index'))

    return render_template('movies/update.html', form=form, movie=movie)

app/templates/movies/detail.html
{% extends 'core/base.html' %}

{% block hero %}
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        {{ movie.name }}
      </h1>
      <h2 class="subtitle">
        Este é um filme da categoria <b>{{ movie.category.name }}</b>
      </h2>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
  <button class="button is-info is-light"><a href="{{ url_for('movies.formUpdate', movie_id=movie.id) }}">Editar</a></button>
{% endblock %}

app/templates/movies/form.html
{% extends 'core/base.html' %}

{% block hero %}
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Filme
      </h1>
      <h2 class="subtitle">
        Informe os dados do novo filme
      </h2>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
  {% if error %}
  <div class="notification is-danger">
    {{ error }}
  </div>
  {% endif %}

  <form action="{{ url_for('movies.formCreate') }}" method="POST">
    {{ form.csrf_token }}
    <div class="field">
      <label class="label">Name</label>
      <div class="control">
        {{ form.name(size=20, class_="input") }}
      </div>
    </div>
    <div class="field">
      <label class="label">Categoria</label>
      <div class="select">
        {{ form.category() }}
      </div>
    </div>
    <div class="control">
      <button class="button is-primary">Salvar</button>
    </div>    
  </form>
{% endblock %}

app/templates/movies/list.html
{% extends 'core/base.html' %}

{% block hero %}
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Filmes
      </h1>
      <h2 class="subtitle">
        Escolha os filmes
      </h2>
    </div>
  </div>
</section>
{% endblock %}
{% block content %}
  {% for movie in movies %}
  <button class="button is-light is-large"><a href="{{ url_for('movies.detail', movie_id=movie.id) }}">{{ movie.name }}</a></button>
  {% endfor %}
  <button class="button is-info is-light is-large"><a href="{{ url_for('movies.formCreate') }}">Novo filme</a></button>
{% endblock %}

app/templates/movies/update.html
{% extends 'core/base.html' %}

{% block hero %}
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Filme
      </h1>
      <h2 class="subtitle">
        Informe os dados do novo filme
      </h2>
    </div>
  </div>
</section>
{% endblock %}

{% block content %}
  {% if error %}
  <div class="notification is-danger">
    {{ error }}
  </div>
  {% endif %}

  <form action="{{ url_for('movies.formUpdate', movie_id=movie.id) }}" method="POST">
    {{ form.csrf_token }}
    <div class="field">
      <label class="label">Name</label>
      <div class="control">
        {{ form.name(size=20, class_="input") }}
      </div>
    </div>
    <div class="field">
      <label class="label">Categoria</label>
      <div class="select">
        {{ form.category() }}
      </div>
    </div>
    <div class="control">
      <button class="button is-primary">Salvar</button>
    </div>    
  </form>
{% endblock %}