app/modules/core/models.py
from app import db
from peewee import Model


'''
class: Base Model
'''
class BaseModel(Model):

  class Meta:
    # Indica em qual banco de dados a tabela sera criada (obrigatorio). Neste caso, utilizamos o banco 'movies.db'
    database = db

app/modules/core/controllers.py
import peewee
from flask import Blueprint, render_template, request, redirect, url_for, session



blueprint = Blueprint('core', __name__, url_prefix='/')


@blueprint.route('/', methods=['GET'])
def index():
  return render_template('core/index.html')

app/modules/users/controllers.py
import peewee, os, base64
from app import app
from flask import Blueprint, render_template, request, redirect, url_for, session
from werkzeug.utils import secure_filename

from .models import User
from .forms import SignInForm, SignUpForm


blueprint = Blueprint('users', __name__, url_prefix='/users')


# Set the route and accepted methods
@blueprint.route('/login', methods=['GET', 'POST'])
def login():
  form = SignInForm(request.form)
  if request.method == 'GET':
    return render_template('users/login.html', form=form)
  else:
    if form.validate_on_submit():
      try:
        user = User.get(email=form.email.data, password=form.password.data)
        print(user.photo)
        if user:
          session['user_id'] = user.id
          session['name'] = user.name
          session['email'] = user.email
          session['photo'] = user.photo
        else:
          return render_template('users/login.html', error='Email ou senha incorretos!', form=form)
      except peewee.IntegrityError:
        return render_template('users/login.html', error='Email ou senha incorretos!', form=form)
      return redirect(url_for('movies.index'))

    return render_template('users/login.html', form=form)


# Set the route and accepted methods
@blueprint.route('/signup', methods=['GET', 'POST'])
def signup():
  form = SignUpForm()
  if request.method == 'GET':
    return render_template('users/signup.html', form=form)
  else:
    if form.validate_on_submit():
      try:
        photo = form.photo.data
        filename = secure_filename(photo.filename)
        path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        photo.save(path)
        
        user = User.create(name=form.name.data, email=form.email.data, password=form.password.data, photo=filename, is_admin=form.is_admin.data)
        session['user_id'] = user.id
        session['name'] = user.name
        session['email'] = user.email
        session['photo'] = filename
      except peewee.IntegrityError:
        return render_template('users/signup.html', error='Usuário já cadastrado!', form=form)
      return redirect(url_for('movies.index'))
    return render_template('users/signup.html', form=form)

@blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
  session.pop('user_id', None)
  session.pop('name', None)
  session.pop('email', None)
  session.pop('photo', None)
  return redirect(url_for('movies.index'))


@blueprint.route('/images/')
def photo():
  return redirect(url_for('static', filename=f'uploads/{session["photo"]}'), code=301)

app/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bulma.min.css') }}">
  {% block header %}{% endblock %}
  <script>
    document.addEventListener('DOMContentLoaded', () => {

    // Get all "navbar-burger" elements
    const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

    // Check if there are any navbar burgers
    if ($navbarBurgers.length > 0) {

      // Add a click event on each of them
      $navbarBurgers.forEach( el => {
        el.addEventListener('click', () => {

          // Get the target from the "data-target" attribute
          const target = el.dataset.target;
          const $target = document.getElementById(target);

          // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
          el.classList.toggle('is-active');
          $target.classList.toggle('is-active');

        });
      });
    }

  });
  </script>
  <title>DWEB - FlaskMovies</title>
</head>
<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <img src="{{ url_for('static', filename='images/logo.png') }}" width="112" height="28">
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="{{ url_for('movies.index') }}">
          Filmes
        </a>
        <a class="navbar-item" href="{{ url_for('categories.index') }}">
          Categorias
        </a>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if session['email'] %}
            <figure class="image is-32x32">
              <img class="is-rounded" src="{{ url_for('users.photo') }}">
            </figure>
            <span class="navbar-item" href="{{ url_for('categories.index') }}">{{ session['name'] }}</span>
            <a class="button is-primary" href="{{ url_for('users.logout') }}">
              <strong>Logout</strong>
            </a>
            {% else %}
            <a class="button is-primary" href="{{ url_for('users.signup') }}">
              <strong>Sign up</strong>
            </a>
            <a class="button is-light" href="{{ url_for('users.login') }}">
              Log in
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>
  {% block hero %}{% endblock %}
  <section class="section">
    <div class="container">
      {% block content %}{% endblock %}
    </div>
  </section>
</body>
</html>

app/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
  <h1 class="title">
    FlaskMovies
  </h1>
  <p class="subtitle">
    Bem vindo!
  </p>
  <p>
    <img src="{{ url_for('static', filename='images/tenor.gif') }}"/>
  </p>
{% endblock %}